import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Sidebar from "@/components/sidebar/sidebar";

export const metadata: Metadata = {
  title: "Mail Flow",
  description: "Generated by create next app",
  icons:{
    icon: "/logo.svg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <Navbar/>
      <div>
        <Sidebar/>
        <body>{children}</body>
      </div>
    </html>
  );
}
